Gamify-IT/lecturer-interface

.nginx/compose/nginx-dev.conf, .nginx/compose/nginx.conf, README.md, docker-compose-dev.yaml, docker-compose.yaml, package.json, vue.config.js
=> add Docker Compose files

.nginx/compose/nginx-dev.conf, .nginx/compose/nginx.conf, docker-compose-dev.yaml, docker-compose.yaml, src/ts/models.ts, tests/unit/AreaBox.spec.ts
=> change moorhuhn to chickenshock to avoid legal problems

src/components/EditChickenshockConfigurationModal.vue, src/components/EditNPCModal.vue, src/ts/course-rest-client.ts, src/ts/models.ts, src/views/CourseView.vue, src/views/MinigameTasksView.vue, tests/unit/CourseView.spec.ts, tests/unit/EditChickenshockConfigurationModal.spec.ts, tests/unit/MinigameTasksView.spec.ts, tests/unit/NPCsView.spec.ts, tests/unit/WorldView.spec.ts
- display minigame index instead of id in success changed toast
- when entering wrong semester request the course info again to override wrong semester
=> Fix code smells, fix little bugs

src/ts/course-rest-client.ts, src/views/CourseView.vue, src/views/CoursesView.vue
Closes Gamify-IT/issues#214
I am a bit lost in designing. Please leave feedback if you have suggestions.
=> Implement course deletion

src/components/AreaBox.vue, src/components/EditableStringAttribute.vue, src/ts/models.ts, src/views/CourseView.vue, src/views/MinigameTasksView.vue, src/views/NPCsView.vue, tests/unit/AreaBox.spec.ts, tests/unit/EditChickenshockConfigurationModal.spec.ts, tests/unit/MinigameTasksView.spec.ts, tests/unit/NPCsView.spec.ts
=> Add editable descriptions to both NPC and minigame tasks

src/components/MapImageModal.vue, src/config.ts, src/ts/models.ts, src/views/MinigameTasksView.vue, src/views/NPCsView.vue, src/views/WorldView.vue
=> Add image spots

src/components/EditCrosswordpuzzleModal.vue, src/config.ts, src/ts/crosswordpuzzle-rest-client.ts, src/ts/models.ts, src/views/MinigameTasksView.vue
=> Add crosswordpuzzle configuration

.nginx/compose/nginx-dev.conf, .nginx/compose/nginx.conf, docker-compose-dev.yaml, docker-compose.yaml, src/components/EditFinitequizConfigurationModal.vue, src/config.ts, src/ts/finitequiz-rest-client.ts, src/ts/models.ts, src/views/MinigameTasksView.vue
=> Add finitequiz configuration

.eslintrc.js, .github/workflows/deploy-docker-image-on-release.yml, .nginx/compose/nginx-dev.conf, src/App.vue, src/components/AreaBox.vue, src/components/CloneCourseModal.vue, src/components/CourseSidebarMenu.vue, src/components/CreateCourseModal.vue, src/components/EditChickenshockConfigurationModal.vue, src/components/EditableStringAttribute.vue, src/ts/models.ts, src/ts/validate.ts, src/views/CourseView.vue, src/views/CoursesView.vue, src/views/MinigameTasksView.vue, src/views/NPCsView.vue, src/views/WorldView.vue, tests/unit/AreaBox.spec.ts, tests/unit/CourseView.spec.ts, tests/unit/CoursesView.spec.ts
Closes https://github.com/Gamify-IT/issues/issues/217
=> improve a11y

src/components/EditMinigameModals/EditChickenshockConfigurationModal.vue, src/components/EditMinigameModals/EditFinitequizConfigurationModal.vue
Removed the need to press add in the add question modal.
=> Improve minigame modals

package-lock.json, package.json, src/components/EditMinigameModals/EditChickenshockConfigurationModal.vue, src/components/EditMinigameModals/EditCrosswordpuzzleModal.vue, src/components/EditMinigameModals/EditFinitequizConfigurationModal.vue, src/components/ImportExportConfiguration.vue, src/ts/import-configuration.ts
=> Add import and export of minigame configurations

.nginx/compose/nginx-dev.conf, docker-compose-dev.yaml, src/components/EditMinigameModals/EditChickenshockConfigurationModal.vue, src/components/EditMinigameModals/EditCrosswordpuzzleModal.vue, src/components/EditMinigameModals/EditFinitequizConfigurationModal.vue, src/ts/import-configuration.ts, src/ts/models/chickenshock-models.ts, tests/unit/EditChickenshockConfigurationModal.spec.ts
Please check if cloning still works now. We didn't change it. @Aaron2000119 @maexled 
How to test: Create a chickenshock game with a time (default time is 50), test it by going to http://localhost/minigames/chickenshock#{id}
Closes Gamify-IT/issues#239
=> Add chickenshock dynamic time

.nginx/compose/nginx-dev.conf, .nginx/compose/nginx.conf, docker-compose-dev.yaml, docker-compose.yaml
Part of Gamify-IT/issues#274 \
Now keycloak and the landing page is added to the `docker-compose*.yaml` files, so the login works correctly
=> add keycloak and landing page

docker-compose-dev.yaml, docker-compose.yaml, src/components/EditMinigameModals/EditChickenshockConfigurationModal.vue, src/components/EditMinigameModals/EditCrosswordpuzzleModal.vue, src/components/EditMinigameModals/EditFinitequizConfigurationModal.vue
=> Export configuration files as json file

src/components/Sidebar/CourseSidebarMenu.vue, src/views/CourseView.vue, src/views/CoursesView.vue, src/views/MinigameTasksView.vue, src/views/NPCsView.vue, src/views/WorldView.vue
=> Add some useful hints to show the user what he can do on the views

.github/workflows/deploy-docker-image-on-release.yml, src/components/EditBookModal.vue, src/components/MapImageModal.vue, src/components/Sidebar/CourseSidebarMenu.vue, src/config.ts, src/router/index.ts, src/ts/models/overworld-models.ts, src/ts/rest-clients/book-rest-client.ts, src/views/BooksView.vue, src/views/CourseView.vue, tests/unit/AreaBox.spec.ts, tests/unit/BooksView.spec.ts, tests/unit/NPCsView.spec.ts, tests/unit/WorldView.spec.ts
Closes Gamify-IT/issues#301
How to test: 
As long Gamify-IT/overworld-backend#42 is not merged, you have to build the overworld-backend image `ghcr.io/gamify-it/overworld-backend:main` yourself:
- Checkout the branch feature/add-books-in-courses from the overworld-backend
- switch to the root directory of the overworld-backend project
- run `docker build -t ghcr.io/gamify-it/overworld-backend:main . `
Edit docker-compose:
- set `setup.image` to `ghcr.io/gamify-it/test-data:maintenance-book-test-data`
Start the docker-compose:
- run `docker-compose up --build`
Execute test plans created in Gamify-IT/docs#169
=> Integrate books in area and make them configurable

.nginx/compose/nginx-dev.conf, docker-compose-dev.yaml, docker-compose.yaml, src/components/EditMinigameModals/EditChickenshockConfigurationModal.vue, src/components/EditMinigameModals/EditFinitequizConfigurationModal.vue, tests/unit/AreaBox.spec.ts
Display detailed error messages on bad requests by chickenshock backend, let the time input field display the current state
=> Handle time error on chickenshock configuration

src/config.ts
=> add new hash of new maps

tests/unit/AreaBox.spec.ts
=> Add unit test for changing active switch

src/components/CourseComponents/CloneCourseModal.vue, src/ts/models/overworld-models.ts
to test use the https://github.com/Gamify-IT/overworld-backend/tree/feature/dont-interupt-cloning and stop some minigame backends.
=> add error messages toast

src/components/MapImageModal.vue
=> fix books map filename

src/ts/statistics/overworld-statistics.ts, src/views/MinigameTaskStatisticView.vue
Closes Gamify-IT/issues#459
Needs Gamify-IT/overworld-backend#68
=> Make highscore distribution chart to a line chart

Dockerfile, docker-compose-dev.yaml, docker-compose.yaml, src/components/CourseComponents/CloneCourseModal.vue, src/components/CourseComponents/CreateCourseModal.vue, src/components/EditMinigameModals/EditBugfinderConfigurationModal.vue, src/components/EditMinigameModals/EditChickenshockConfigurationModal.vue, src/components/EditMinigameModals/EditCrosswordpuzzleModal.vue, src/components/EditMinigameModals/EditFinitequizConfigurationModal.vue, src/components/EditMinigameModals/EditTowercrushConfigurationModal.vue, src/components/MinigameStatisticComponents/FiniteQuizStatisticBox.vue, src/components/Sidebar/CourseSidebarMenu.vue, src/components/WorldComponents/AreaBox.vue, src/ts/models/overworld-models.ts, src/views/BooksView.vue, src/views/CourseView.vue, src/views/MinigameTasksView.vue, src/views/NPCsView.vue, tests/unit/NPCsView.spec.ts
Part of https://github.com/Gamify-IT/issues/issues/498
https://sonar.sqa-kube-cluster4.cloudns.nz/dashboard?id=lecturer-interface
**Please test is everything is still working as intendet**
=> Fix sonarqube issues

src/views/CoursesView.vue
=> Add button to return to landing page from lecturer interface

src/components/CourseStatisticBox.vue, src/components/MinigameStatisticComponents/FiniteQuizStatisticBox.vue, src/ts/models/statistic-models.ts, src/ts/rest-clients/course-statistics-rest-client.ts, src/ts/statistics/course-statistics.ts, src/ts/statistics/finitequiz-statistics.ts, src/ts/statistics/overworld-statistics.ts, src/views/CourseView.vue
Closes Gamify-IT/issues#461
To test together with the corresponding pull request of Gamify-IT/overworld-backend#74, edit the docker-compose.yaml file, uncomment the image of overworld-backend, and add build with your path of the overworld-backend repo with the target branch:
```
overworld-backend:
container_name: overworld-backend
#image: ghcr.io/gamify-it/overworld-backend:main
build: /home/max/gamifyit/overworld-backend/.
restart: always
pull_policy: always
expose:
- "80"
depends_on:
- overworld-db
environment:
- POSTGRES_USER=postgres
- POSTGRES_PASSWORD=postgres
- POSTGRES_URL=postgresql://overworld-db:5432/postgres
- CHICKENSHOCK_URL=http://chickenshock-backend/api/v1
- CROSSWORDPUZZLE_URL=http://crosswordpuzzle-backend/api/v1
- FINITEQUIZ_URL=http://finitequiz-backend/api/v1
- …
```
=> Create course statistics

src/components/EditMinigameModals/EditRegexGameModal.vue, src/shims-vue.d.ts
- added warning when configuring regexgame
- fixed error when trying to save the configuration
=> Bugfix regexgame configuration

.nginx/compose/nginx-dev.conf, .nginx/compose/nginx.conf, docker-compose-dev.yaml, src/components/EditMinigameModals/EditTowerDefenseConfigurationModal.vue, src/config.ts, src/ts/models/overworld-models.ts, src/ts/models/towerdefense-models.ts, src/ts/rest-clients/towerdefense-rest-client.ts, src/views/MinigameTasksView.vue
The necessary files for tower defense have been added to the lecturer interface
=> created files for tower defense

.nginx/compose/nginx-dev.conf, .nginx/compose/nginx.conf, docker-compose-dev.yaml, src/components/EditMinigameModals/EditChickenshockConfigurationModal.vue, src/components/EditMinigameModals/EditCrosswordpuzzleModal.vue, src/components/EditMinigameModals/EditFinitequizConfigurationModal.vue, src/components/EditMinigameModals/EditMemoryConfigurationModal.vue, src/components/EditMinigameModals/EditRegexGameModal.vue, src/components/EditMinigameModals/EditTowerDefenseConfigurationModal.vue, src/components/EditMinigameModals/EditTowercrushConfigurationModal.vue, src/ts/import-configuration.ts, src/ts/models/regexgame-models.ts, src/ts/rest-clients/regexgame-rest-client.ts
fixed import and export for all minigame configs
=> Fixed import/export functionality 

docker-compose-dev.yaml, src/components/EditMinigameModals/EditChickenshockConfigurationModal.vue, src/components/EditMinigameModals/EditCrosswordpuzzleModal.vue, src/components/EditMinigameModals/EditFinitequizConfigurationModal.vue, src/components/EditMinigameModals/EditTowerDefenseConfigurationModal.vue, src/components/EditMinigameModals/EditTowercrushConfigurationModal.vue, src/components/ImportExportConfiguration.vue
Changed input fields and text display to better support multiline/long text
=> Feature multiline questions

src/views/MinigameTasksView.vue
Each minigame can now be played from the lecturer interface.
=> Minigame Test Button for Lecturers
